import {
  PROJECT_1_URL,
  PROJECT_1_GITHUB,
  PROJECT_2_URL,
  PROJECT_2_GITHUB,
  PROJECT_3_URL,
  PROJECT_3_GITHUB,
  PROJECT_4_URL,
  PROJECT_4_GITHUB,
} from "./env";

const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/icons/work.svg",
  kind: "folder",
  children: [
    {
      id: 5,
      name: "SHB Firm Manager",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-10 left-5",
      windowPosition: "top-[5vh] left-5",
      children: [
        {
          id: 1,
          name: "SHB Firm Manager.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "Production legal practice ops for Chambers of SHB Legal. Matters, hearings, diary, documents, and recurring court updates.",
            "Railway workers and scrapers cover eCourts, Bombay HC, and MahaRERA/REAT. Automation stays review-only until a human signs off.",
            "Stack: Next.js, Supabase, TypeScript, Railway workers, Python scrapers. Live diary work runs on Asia/Kolkata dates.",
          ],
        },
        {
          id: 2,
          name: "shb-case-manager",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_1_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "shb.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/shb.webp",
          imageMobUrl: "/projects/mobile/shb-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_1_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 6,
      name: "Veryfy",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-52 right-80",
      windowPosition: "top-[20vh] left-7",
      children: [
        {
          id: 1,
          name: "Veryfy.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 right-10",
          description: [
            "Verification cloud at veryfy.cloud with client and control portals for review-led workflows.",
            "Email and agent lanes run through Resend and AgentMail. Source records stay untouched; editable review state sits beside them.",
            "Stack: Next.js, Supabase, Resend, AgentMail, Vercel.",
          ],
        },
        {
          id: 2,
          name: "veryfy.cloud",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_2_URL,
          position: "top-20 left-20",
        },
        {
          id: 4,
          name: "veryfy.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 left-80",
          imageUrl: "/projects/veryfy.webp",
          imageMobUrl: "/projects/mobile/veryfy-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_2_GITHUB,
          position: "top-60 left-5",
        },
      ],
    },
    {
      id: 7,
      name: "Accord",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-10 left-80",
      windowPosition: "top-[33vh] left-7",
      children: [
        {
          id: 1,
          name: "Accord.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "An MCP gateway and control plane for developer previews. Policies are explicit, execution is bounded, and decisions leave receipts.",
            "Built for agent work that still needs a human way back — approvals, budgets, and inspectable outcomes.",
            "Live at mcp.edenbuilds.me. Stack: TypeScript, MCP, Next.js, Vercel.",
          ],
        },
        {
          id: 2,
          name: "mcp.edenbuilds.me",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_3_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "accord.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/accord.webp",
          imageMobUrl: "/projects/mobile/accord-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_3_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 8,
      name: "Blackbox",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-52 left-5",
      windowPosition: "top-[46vh] left-7",
      children: [
        {
          id: 1,
          name: "Blackbox.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "A zero-dependency flight recorder for coding agents. Claude Code and Codex transcripts become one append-only event log.",
            "Query by session, file, command, model, and spend. Source transcripts stay untouched.",
            "Part of the Eden agent surface alongside Marshall, Perimeter, Omni, Chancery, and Metr.",
          ],
        },
        {
          id: 2,
          name: "blackbox",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_4_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "blackbox.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/blackbox.webp",
          imageMobUrl: "/projects/mobile/blackbox-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_4_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
  ],
};

const ABOUT_LOCATION = {
  id: 2,
  type: "about",
  name: "About",
  icon: "/icons/info.svg",
  kind: "folder",
  children: [
    {
      id: 4,
      name: "about-eden.txt",
      icon: "/images/txt.webp",
      kind: "file",
      fileType: "txt",
      position: "top-60 left-5",
      subtitle: "Eden Builds",
      description: [
        "Eden Builds is a one-person studio shipping production apps for real clients, plus reputation through upstream open-source merges and public agent tools.",
        "Active work spans SHB Firm Manager, Veryfy, Praya Studio, the Vikram Shah archive, and agent infra like Blackbox, Marshall, Perimeter, Omni, Chancery, and Metr.",
        "Also: client sites for UDW, Exceleon, Chirayu, Tulip, and Count. Design stays premium and understated — strong type, less text, everything clickable is clickable.",
      ],
    },
  ],
};

const RESUME_LOCATION = {
  id: 3,
  type: "resume",
  name: "Resume",
  icon: "/icons/file.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "Resume.pdf",
      icon: "/images/pdf.webp",
      kind: "file",
      fileType: "pdf",
    },
  ],
};

const TRASH_LOCATION = {
  id: 4,
  type: "trash",
  name: "Trash",
  icon: "/icons/trash.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "trash1.png",
      icon: "/images/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-10 left-10",
      imageUrl: "/images/trash-1.webp",
    },
    {
      id: 2,
      name: "trash2.png",
      icon: "/images/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-40 left-80",
      imageUrl: "/images/trash-2.webp",
    },
  ],
};

export const locations = {
  work: WORK_LOCATION,
  about: ABOUT_LOCATION,
  resume: RESUME_LOCATION,
  trash: TRASH_LOCATION,
};
